#Backend
backend = "glx";
#glx-no-stencil = true;
glx-copy-from-front = false;
vsync = true;

#Opacity
active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;
inactive-dim = 0.3;
inactive-dim-fixed = true;

#Blur
blur-method = "kernel";
blur-strength = 5;

#Shadows
shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.7;

#Exclude
opacity-rule = [
	"100:class_g = 'firefox'",
	"100:class_g = 'mpv'",
	"100:class_g = 'st-256color'",
	"90:class_g = 'alacritty'"
];

#Fading
fading = true;
fade-delta = 4;
fade-in-step = 0.03;
fade-out-step = 0.03;
